### ISSUE TITLE
asus xq-c100f cannot work

### ISSUE THREAD

**Issue by JunwayGuo** [CaseySJ/Aquantia-macOS-Patches#3]
OS：Sonoma 14.2.1
Ethernet card：Asus XQ-C100F
Have opened VT-D，set1 and set2 I tried them all。
The result is that the network card cannot be recognized
What else should I do？

![image](https://github.com/CaseySJ/Aquantia-macOS-Patches/assets/31336068/151cd6fa-2934-4a5a-9c5f-7a4805cfad07)

**Comment by CaseySJ** [comment]
This problem occurs because the Asus C100F (device ID 0x00B1) is not natively support in macOS. Nevertheless we can spoof it to device ID 0x07B1 with a kext patch and a device property.

Solution is provided here:
https://www.tonymacx86.com/threads/problem-with-asus-xg-c100f-sonoma.328390/post-2392733
